name: Workflow for HEL Bikes App Project

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run tests upon push or pull requests
        run: |
          cd bike-app
          npm i
          npm run test

      - name: Build and deploy frontend code
        run: |
          cd bike-app
          npm i
          npm i --global surge
          npm run build
          cd dist
          cp index.html 200.html
  deploy:
    name: Deplpoy to surge
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to surge
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'https://helbikeapp.surge.sh/'
          project: '/bike-app/dist'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}